package com.notification.dutynotifier.entity.auditLog;

public enum AuditAction {
    DUTY_CREATED,
    DUTY_UPDATED,
    DUTY_DELETED,
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DELETED,
    SCHEDULE_UPLOADED,
    NOTIFICATION_SENT,
    LOGIN,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    SCHEDULE_UPLOAD_FAILED
}
